---
- hosts: all
  become: yes
  roles:
    - role: elastic.beats
  vars:
    beats_version: 7.6.2
    beat: filebeat
    beat_conf:
      filebeat:
        inputs:
          - type: log
            enabled: true
            paths:
              - /var/log/*.log      
        config:
            modules:
               path: ${path.config}/modules.d/*.yml
               reload.enabled: false     
      setup:        
        template:      
            settings:  
               index.number_of_shards: 1
      output:
        logstash:  
            hosts: ["plabmonv002:5044"]             
      processors:
        - add_host_metadata: ~
        - add_cloud_metadata: ~
        - add_docker_metadata: ~
        - add_kubernetes_metadata: ~
