---
- hosts: all
  become: yes
  roles:
    - role: elastic.beats
  vars:
    beats_version: 7.6.2
    beat: filebeat
    beat_conf:
      filebeat:
        inputs:
          - type: log
            enabled: true
            paths:
              - /var/log/*.log
  tasks:
    - name: Load filebeat index template in Elasticsearch
      command: /usr/share/filebeat/bin/filebeat setup --index-management -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["plabmonv002:9200"]'
    - name: Unalias RM
      command: unalias rm
    - name: Delete default filebeat configuration file
      command: rm -f /etc/filebeat/filebeat.yml
    - name: Install plab filebeat configuration file
      template:
        src: /home/plab.ansible/plab_git/plab/Beats/filebeat.yml
        dest: /etc/filebeat/filebeat.yml
    - name: restart filebeat
      systemd:
        enabled: yes
        state: restarted
        name: filebeat.service
